server:
  port: 3333

logging:
  level:
    org:
    pl:
      futurecollars:
        invoicing: INFO
        invoicing.db: DEBUG

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
      active: file
  flyway:
      enabled: false
  security:
      user:
        name: ola
        password: qwerty123

invoicing-system:
  allowedOrigins: http://localhost:4200
  csrf:
      disable: true