server:
  port: 3333

invoicing-system:
    database:
      type: file
      dbPath: invoice.json
      idDbPath: id.txt

logging:
  level:
    org:
    pl:
      futurecollars:
        invoicing: INFO
        invoicing.db: DEBUG

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
      active: jpa-flyway
  flyway:
      enabled: false