server:
  port: 8888

invoicing-system:
    database:
      type: file
      dbPath: invoice.json
      idDbPath: id.txt

logging:
  level:
    pl:
      futurecollars:
        invoicing: INFO
        invoicing.db: DEBUG