server:
  port: 3333

logging:
  level:
    org:
    pl:
      futurecollars:
        invoicing: INFO
        invoicing.db: DEBUG

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
      active: sql
  flyway:
      enabled: false