package pl.futurecollars.invoicing.model;

import static javax.persistence.CascadeType.ALL;

import com.fasterxml.jackson.annotation.JsonIgnore;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Entity
@NoArgsConstructor
@Builder
@AllArgsConstructor

public class InvoiceEntry {
  @Id
  @JoinColumn(name = "entry_id")
  @JsonIgnore
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @ApiModelProperty(value = "Invoice entry id (generated by application)", required = true, example = "1")
  private Long id;
  @ApiModelProperty(value = "product description", example = "MacPro/ 13'' M2 8 GB")
  private String description;

  @ApiModelProperty(value = "Number of items", required = true, example = "85")
  private BigDecimal quantity;

  @ApiModelProperty(value = "product net price", example = "12299.99")
  private BigDecimal netPrice;

  @ApiModelProperty(value = "product tax value", required = true)
  @Builder.Default
  private BigDecimal vatValue = BigDecimal.ZERO;

  @Enumerated(EnumType.STRING)
  @ApiModelProperty(value = "Tax rate", required = true)
  private Vat vatRate;

  @JoinColumn(name = "expense_related_to_car")
  @OneToOne(fetch = FetchType.EAGER, cascade = ALL, orphanRemoval = true)
  @ApiModelProperty(value = "Car this expense is related to, empty if expense is not related to car")
  private Car expenseRelatedToCar;
}
