# This workflow uses actions that are not certified by GitHub.
name: CI

  # Controls when the action will run.
on:
    # Triggers the workflow on push or pull request events but only for the master branch
    push:
      branches: [ task_* ]
    pull_request:
      branches: [ task_* ]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    build:
      name: invoicing-system-build
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v3
        - name: Start MongoDB
          uses: supercharge/mongodb-github-action@1.3.0
          with:
            mongodb-version: 4.4

        - name: Build with Gradle
          run: ./gradlew build

        - name: Archive reports
          if: always()
          uses: actions/upload-artifact@v2
          with:
             name: reports
             path: build/reports/**
